"""
Django settings for FM BRAVA project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
# Importando Librerias para caonfiguracion base del proyecto
import json, os
from django.contrib.messages import constants as messages
from django.core.exceptions import ImproperlyConfigured

# Configuracion de Messages
MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger'
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = *********

# Application definition

DJANGO_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  
    'rest_framework',
    'rest_framework.authtoken',  # Necesario para manejar tokens
    'rest_framework_simplejwt',
    # CORS Headers
    'corsheaders',
)

# Aplicaciones de Terceros
THIRD_PARTY_APPS = (
    'crispy_forms',
    'crispy_bootstrap5', 
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'social_django', 
    'dj_rest_auth', 
    # Proveedores de Users, Google
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',  # Para Facebook
)

LOCAL_APPS = (
    'users',
    'core',
    'blogs',
    'programs',
    'adverstisements',
)

# Aplicaciones Locales
INSTALLED_APPS = THIRD_PARTY_APPS + DJANGO_APPS + LOCAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # 🚀 Agrega esta línea aquí
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Solo una vez
    'social_django.middleware.SocialAuthExceptionMiddleware',
]


ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/"templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "users.User"

SITE_ID = 1  # Asegúrate de que esto esté configurado

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

LOGIN_REDIRECT_URL = '/home/'
LOGIN_URL = '/users/login/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
# Aquí defines el directorio donde Django colocará los archivos estáticos en producción
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Debe ser diferente de STATICFILES_DIRS

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

CSRF_TRUSTED_ORIGINS = [
    "https://brava.okarol.com",
    "http://127.0.0.1",
    "http://localhost",
    "https://agu.dev.demo.okarol.com",
    "https://fmbravasalta.com.ar"
]

# Configuración de CORS
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Permitir peticiones desde React
    "http://127.0.0.1:3000",
    "https://agu.dev.demo.okarol.com",
    "https://fmbravasalta.com.ar"
]

# Si quieres permitir todas las solicitudes desde cualquier origen (no recomendado en producción)
# CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True  # Permitir que se envíen cookies y autenticación

# Para PERMITIR LA CONFIGURACION DE LOS USUARIOS
SESSION_ENGINE = "django.contrib.sessions.backends.db"  # Usa la base de datos para almacenar sesiones
SESSION_COOKIE_HTTPONLY = True  # Protege la cookie de sesión
SESSION_COOKIE_SECURE = False  # Cambia a True en producción con HTTPS
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Permite que la sesión persista después de cerrar el navegador

# REST_USE_JWT = True  # Activa JWT en dj-rest-auth

# DJANGO_ALLAUTH_PROVIDERS = ["google", "facebook"]

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),  # Expira en 1 día
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

# SOCIALACCOUNT_PROVIDERS = {
#     'facebook': {
#         'APP': {
#             'client_id': '',        # Reemplaza con tu App ID
#             'secret': '',       # Reemplaza con tu App Secret
#             'key': '',                       # Opcional
#         },
#         'SCOPE': ['email', 'public_profile'],
#         'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
#         'METHOD': 'oauth2',
#         'VERIFIED_EMAIL': True,
#     },
#     'google': {
#         'APP': {
#             'client_id': '', # Estas variables deberian estar en .env   
#             'secret': '',
#             'key': ''
#         },
#         'SCOPE': ['profile', 'email'],
#         'AUTH_PARAMS': {'access_type': 'online'},
#     }
# }

import environ # Cargamos lectura de .ENV
import os

# Si verifica esta expreion, estamos en entornode desarrollo
env = environ.Env()
#environ.Env.read_env() # Lee el archivo .env automaticamente
# Cargamos las variables de entorno desde el archivo .env

environ.Env.read_env(os.path.join(BASE_DIR, ".env"))


# Cliente de Google (necesario para la vista personalizada)
GOOGLE_CLIENT_ID = env('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = env('GOOGLE_CLIENT_SECRET')
# Cliente de Facebook (necesario para la vista personalizada)
FACEBOOK_APP_ID = env('FACEBOOK_APP_ID')
FACEBOOK_APP_SECRET = env('FACEBOOK_APP_SECRET')
FACEBOOK_REDIRECT_URI = env('FACEBOOK_REDIRECT_URI')
# Cliente de Spotify (necesario para la vista personalizada)
SPOTIFY_CLIENT_ID = env('SPOTIFY_CLIENT_ID')
SPOTIFY_CLIENT_SECRET = env('SPOTIFY_CLIENT_SECRET')
# Clientes de NEWAPI (necesario para las vista personalizadas)
NEWS_API_KEY=env('NEWS_API_KEY')

# Configuración adicional
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'  # Para evitar doble verificación
ACCOUNT_EMAIL_REQUIRED = True
# settings.py
ACCOUNT_USERNAME_REQUIRED = False  # No obligar a username
SOCIALACCOUNT_AUTO_SIGNUP = True  # Crear usuario automáticamente
ACCOUNT_EMAIL_VERIFICATION = 'none'  # No verificar email por correo
