# Generated by Django 5.1.6 on 2025-02-17 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(help_text='Una breve descripción sobre el programa')),
                ('start_time', models.DateTimeField(help_text='Fecha y hora de inicio del programa')),
                ('end_time', models.DateTimeField(help_text='Fecha y hora de fin del programa')),
                ('category', models.CharField(choices=[('musica', 'Música'), ('deporte', 'Deporte'), ('noticias', 'Noticias'), ('cultura', 'Cultura')], help_text='Categoría del programa', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='program_images/')),
                ('host', models.OneToOneField(blank=True, help_text='Encargado del programa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_program', to=settings.AUTH_USER_MODEL)),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_made', to=settings.AUTH_USER_MODEL, verbose_name='Por')),
                ('usuarios', models.ManyToManyField(blank=True, help_text='Usuarios que participan en el programa (elenco)', related_name='programas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
